backend:
  name: github
  repo: PHironaka/country-mart # Path to Github repository
  branch: master # Branch to update (optional; defaults to master)

# publish_mode: editorial_workflow
media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "img"


collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/exhibitions"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}


  